
image: gradle:7.6-jdk19-alpine

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

prepare-release:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_COMMIT_MESSAGE =~ /^Release.*/i
  script:
    - gradle dist
    - echo RELEASE_JOB_URL=$CI_JOB_URL >> release_job_url.env
    - echo JAR_FILE_NAME=$(ls *.jar) >> jar_file_name.env
    - echo JAR_FILE_VERSION=$(echo $JAR_FILE_NAME | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+') >> jar_file_version.env
  artifacts:
    expire_in: 1 hour
    paths:
      - '*.jar'
    reports:
      dotenv:
        - release_job_url.env
        - jar_file_name.env
        - jar_file_version.env
  cache:
    when: 'on_success'
    policy: push
    paths:
      - '*.jar'

create-release:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: prepare-release
      artifacts: true
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_COMMIT_MESSAGE =~ /^Release.*/i
  script:
    - echo $RELEASE_JOB_URL
    - echo $JAR_FILE_NAME
    - echo $JAR_FILE_VERSION
    - |
      release-cli create --name "$CI_PROJECT_TITLE v$JAR_FILE_VERSION" --tag-name $JAR_FILE_VERSION --description "Release $JAR_FILE_VERSION" --assets-link "{\"name\":\"$JAR_FILE_NAME\", \"url\":\"$RELEASE_JOB_URL/artifacts/file/$JAR_FILE_NAME\"}"