image: gradle:7.6-jdk17-alpine

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

debug-working-directory:
  stage: .pre
  only:
    - beta
    - main
    - merge_requests
  script:
    - echo $PWD

debug-file-tree:
  stage: .pre
  only:
    - beta
    - main
    - merge_requests
  script:
    - ls -R

# Template für die Kompilierung der asset-pipeline
.build_asset_pipeline_template: &build_asset_pipeline_template
  stage: build
  only:
    - beta
    - main
    - merge_requests
  script:
    - gradle --build-cache pipeline:build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - pipeline/build
      - .gradle
# Kompilierung der asset-pipeline mit Java 11
build-asset-pipeline-java11:
  image: gradle:7.6-jdk11-alpine
  <<: *build_asset_pipeline_template
# Kompilierung der asset-pipeline mit Java 17
build-asset-pipeline-java17:
  image: gradle:7.6-jdk17-alpine
  <<: *build_asset_pipeline_template
# Kompilierung der asset-pipeline mit Java 21
build-asset-pipeline-java21:
  image: gradle:7.6-jdk21-alpine
  <<: *build_asset_pipeline_template

# Template für die Kompilierung von Modulen
.build_template: &build_template
  stage: build
  only:
    - beta
    - main
    - merge_requests
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

# Template für die Kompilierung des core-Moduls
.build_core_template: &build_core_template
  <<: *build_template
  script:
    - gradle --build-cache core:assemble
# Kompilierung des core-Moduls mit Java 11
build-core-java11:
  image: gradle:7.6-jdk11-alpine
  <<: *build_core_template
# Kompilierung des core-Moduls mit Java 17
build-core-java17:
  image: gradle:7.6-jdk17-alpine
  <<: *build_core_template
# Kompilierung des core-Moduls mit Java 21
build-core-java21:
  image: gradle:7.6-jdk21-alpine
  <<: *build_core_template

# Template für die Kompilierung des desktop-Moduls
.build_desktop_template: &build_desktop_template
  <<: *build_template
  script:
    - gradle --build-cache desktop:assemble
# Kompilierung des desktop-Moduls mit Java 11
build-desktop-java11:
  image: gradle:7.6-jdk11-alpine
  <<: *build_desktop_template
# Kompilierung des desktop-Moduls mit Java 17
build-desktop-java17:
  image: gradle:7.6-jdk17-alpine
  <<: *build_desktop_template
# Kompilierung des desktop-Moduls mit Java 21
build-desktop-java21:
  image: gradle:7.6-jdk21-alpine
  <<: *build_desktop_template

# Template für die Kompilierung des console-Moduls
.build_console_template: &build_console_template
  <<: *build_template
  script:
    - gradle --build-cache console:assemble
# Kompilierung des console-Moduls mit Java 11
build-console-java11:
  image: gradle:7.6-jdk11-alpine
  <<: *build_console_template
# Kompilierung des console-Moduls mit Java 17
build-console-java17:
  image: gradle:7.6-jdk17-alpine
  <<: *build_console_template
# Kompilierung des console-Moduls mit Java 21
build-console-java21:
  image: gradle:7.6-jdk21-alpine
  <<: *build_console_template

test-core:
  stage: test
  only:
    - beta
    - main
    - merge_requests
  script:
    - gradle core:check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  artifacts:
    expire_in: 1 week
    when: always
    reports:
      junit: core/build/test-results/test/TEST-*.xml

test-desktop:
  stage: test
  only:
    - beta
    - main
    - merge_requests
  script:
    - gradle desktop:check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  artifacts:
    expire_in: 1 week
    when: always
    reports:
      junit: desktop/build/test-results/test/TEST-*.xml

test-console:
  stage: test
  only:
    - beta
    - main
    - merge_requests
  script:
    - gradle console:check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  artifacts:
    expire_in: 1 week
    when: always
    reports:
      junit: console/build/test-results/test/TEST-*.xml

test-pipeline:
  stage: test
  only:
    - beta
    - main
    - merge_requests
  script:
    - gradle pipeline:check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  artifacts:
    expire_in: 1 week
    when: always
    reports:
      junit: pipeline/build/test-results/test/TEST-*.xml

test-util:
  stage: test
  only:
    - beta
    - main
    - merge_requests
  script:
    - gradle util:check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  artifacts:
    expire_in: 1 week
    when: always
    reports:
      junit: util/build/test-results/test/TEST-*.xml

prepare-release:
  stage: build
  rules:
    # Der Job soll nur ausgeführt werden, wenn der Branch "main" ist und der Commit-Message mit "Release" beginnt
    - if: $CI_COMMIT_BRANCH == "main" && $CI_COMMIT_MESSAGE =~ /^Release.*/i
  script:
    # Kompilieren der JAR der grafischen Version des Spiels
    - gradle desktop:dist
    # Speichern der URL des "prepare-release" Jobs in den Umgebungsvariablen
    - echo RELEASE_JOB_URL=$CI_JOB_URL >> variables.env
    # Speichern des Namens der JAR der grafischen Version des Spiels in den Umgebungsvariablen
    - DESKTOP_JAR_FILE_NAME=$(ls *.jar)
    - echo DESKTOP_JAR_FILE_NAME=$DESKTOP_JAR_FILE_NAME >> variables.env
    # Speichern der Version des Spiels in den Umgebungsvariablen
    - echo GAME_VERSION=$(echo $DESKTOP_JAR_FILE_NAME | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+') >> variables.env
    # Kompilieren der JAR der nur-Konsolen Version des Spiels
    - gradle console:dist
    # Speichern des Namens der JAR der nur-Konsolen Version des Spiels in den Umgebungsvariablen
    - CONSOLE_JAR_FILE_NAME=$(ls *.jar | grep -v $DESKTOP_JAR_FILE_NAME)
    - echo CONSOLE_JAR_FILE_NAME=$CONSOLE_JAR_FILE_NAME >> variables.env
  artifacts:
    expire_in: never
    paths:
      - '*.jar'
    reports:
      dotenv: variables.env
  cache:
    when: 'on_success'
    policy: push
    paths:
      - '*.jar'

create-release:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: prepare-release
      artifacts: true
  rules:
    # Der Job soll nur ausgeführt werden, wenn der Branch "main" ist und der Commit-Message mit "Release" beginnt
    - if: $CI_COMMIT_BRANCH == "main" && $CI_COMMIT_MESSAGE =~ /^Release.*/i
  script:
    # release-cli:   Erstellen des Releases in GitLab
    # --name:        Der Releasename soll vom Format "[Projekt] v[Version]" sein, bspw. "GaTDsen v1.0.0"
    # --tag-name:    Der Tag des Releases soll die Version als Namen haben, bspw. "1.0.0"
    # --description: Die Beschreibung des Releases
    # --assets-link: Die JAR-Dateien des Spiels, die im "prepare-release" Job erstellt wurden, sollen dem
    #                Release als Assets hinzugefügt werden
    - | 
      release-cli create \
      --name "$CI_PROJECT_TITLE v$GAME_VERSION" \
      --tag-name $GAME_VERSION \
      --description "Release von $CI_PROJECT_TITLE Version $GAME_VERSION!\n- **$DESKTOP_JAR_FILE_NAME**:\n  - Dies ist die vollständige Version des Spiels, mit der sowohl der grafische als auch der headless-Modus ausgeführt werden kann.\n- **$CONSOLE_JAR_FILE_NAME**:\n  - Mit dieser Version des Spiels kann lediglich der headless-Modus ausgeführt werden. Alle grafischen Komponenten des Spiels sind nicht in der Jar enthalten, wodurch die Dateigröße wesentlich kleiner ist." \
      --assets-link "{\"name\":\"$DESKTOP_JAR_FILE_NAME\", \"url\":\"$RELEASE_JOB_URL/artifacts/file/$DESKTOP_JAR_FILE_NAME\"}" \
      --assets-link "{\"name\":\"$CONSOLE_JAR_FILE_NAME\", \"url\":\"$RELEASE_JOB_URL/artifacts/file/$CONSOLE_JAR_FILE_NAME\"}"